# Generated by Django 3.0.4 on 2020-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='Id')),
                ('paid', models.IntegerField(verbose_name='Paid')),
                ('date', models.DateField(verbose_name='Date')),
                ('product', models.CharField(max_length=64, verbose_name='Product')),
            ],
        ),
    ]
