# Generated by Django 3.0.4 on 2020-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.IntegerField(default=0, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
