# Generated by Django 3.0.4 on 2020-03-31 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo01app', '0002_transaction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='userId',
            field=models.IntegerField(default=0, verbose_name='userId'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
