# Generated by Django 3.0.4 on 2020-03-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo01app', '0003_auto_20200331_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='userId',
        ),
    ]
